name: 'IP'
description: 'Infinitely automatically generating parkour plugin.'
author: Efnilite
version: 5.0.1
api-version: 1.16
main: dev.efnilite.ip.IP
depend: [vilib]
softdepend: [floodgate, Vault, PlaceholderAPI, Multiverse-Core, HolographicDisplays, VoidGen]
commands:
    witp:
        aliases: [parkour, ip]
        usage: /<command> [arguments]
        description: Main command for Infinite Parkour